name: Verify

on: [push, pull_request]

env:
  LANG: en_GB.UTF-8
  TZ: Europe/London

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and cache yarn
        uses: bahmutov/npm-install@v1
      - name: Run ESLint
        run: yarn run eslint src/**/*.js

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and cache yarn
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: yarn test
